dataset: cifar100
epoch: 100
optim: sgd
schedule: Cosine
init_lr: 0.1
lr: 0.1
base_class: 60
num_classes: 100
n_way: 5
n_shot: 5
n_sessions: 9
head_type: cosine
pretrained: False
encoder: resnet12
image_size: 32
global_crop_size: 32
local_crop_size: 18
model_path: ''
img_size: 32